// Package agent provides shared types for Windows Print Agent communication.
package agent

import (
	"encoding/json"
	"time"
)

// PrinterConnectionType represents how a printer is connected.
type PrinterConnectionType string

const (
	// ConnectionLocal indicates a locally connected printer (USB, LPT, etc.)
	ConnectionLocal PrinterConnectionType = "local"
	// ConnectionNetwork indicates a network-connected printer
	ConnectionNetwork PrinterConnectionType = "network"
	// ConnectionShared indicates a shared printer from another machine
	ConnectionShared PrinterConnectionType = "shared"
	// ConnectionWSD indicates a Web Services for Devices printer
	ConnectionWSD PrinterConnectionType = "wsd"
	// ConnectionLPD indicates a Line Printer Daemon printer
	ConnectionLPD PrinterConnectionType = "lpd"
)

// PrinterStatus represents the current status of a printer.
type PrinterStatus string

const (
	// PrinterStatusIdle indicates the printer is ready and idle
	PrinterStatusIdle PrinterStatus = "idle"
	// PrinterStatusPrinting indicates the printer is currently printing
	PrinterStatusPrinting PrinterStatus = "printing"
	// PrinterStatusBusy indicates the printer is busy
	PrinterStatusBusy PrinterStatus = "busy"
	// PrinterStatusOffline indicates the printer is offline
	PrinterStatusOffline PrinterStatus = "offline"
	// PrinterStatusError indicates the printer has an error
	PrinterStatusError PrinterStatus = "error"
	// PrinterStatusOutOfPaper indicates the printer is out of paper
	PrinterStatusOutOfPaper PrinterStatus = "out_of_paper"
	// PrinterStatusLowToner indicates the printer has low toner
	PrinterStatusLowToner PrinterStatus = "low_toner"
	// PrinterStatusDoorOpen indicates the printer door is open
	PrinterStatusDoorOpen PrinterStatus = "door_open"
)

// AgentStatus represents the current status of an agent.
type AgentStatus string

const (
	// AgentStatusOnline indicates the agent is online and operational
	AgentStatusOnline AgentStatus = "online"
	// AgentStatusOffline indicates the agent is offline
	AgentStatusOffline AgentStatus = "offline"
	// AgentStatusError indicates the agent has encountered an error
	AgentStatusError AgentStatus = "error"
	// AgentStatusMaintenance indicates the agent is under maintenance
	AgentStatusMaintenance AgentStatus = "maintenance"
	// AgentStatusInitializing indicates the agent is initializing
	AgentStatusInitializing AgentStatus = "initializing"
)

// SessionState represents the current session state of an agent.
type SessionState string

const (
	// SessionStateActive indicates an active session
	SessionStateActive SessionState = "active"
	// SessionStateIdle indicates an idle session
	SessionStateIdle SessionState = "idle"
	// SessionStateDisconnected indicates a disconnected session
	SessionStateDisconnected SessionState = "disconnected"
)

// DiscoveredPrinter represents a printer discovered by an agent.
type DiscoveredPrinter struct {
	// PrinterID is the unique identifier for this printer (generated by server)
	PrinterID string `json:"printer_id,omitempty"`
	// AgentID is the agent that discovered this printer
	AgentID string `json:"agent_id"`
	// Name is the printer name as reported by the OS
	Name string `json:"name"`
	// DisplayName is a human-readable display name
	DisplayName string `json:"display_name,omitempty"`
	// Driver is the printer driver name
	Driver string `json:"driver"`
	// DriverVersion is the printer driver version
	DriverVersion string `json:"driver_version,omitempty"`
	// Port is the printer port (e.g., "USB001", "192.168.1.100", "WSD...")
	Port string `json:"port"`
	// ConnectionType indicates how the printer is connected
	ConnectionType PrinterConnectionType `json:"connection_type"`
	// Status is the current printer status
	Status PrinterStatus `json:"status"`
	// IsDefault indicates if this is the default printer
	IsDefault bool `json:"is_default"`
	// IsShared indicates if this printer is shared
	IsShared bool `json:"is_shared"`
	// ShareName is the network share name (if shared)
	ShareName string `json:"share_name,omitempty"`
	// Location is the printer location
	Location string `json:"location,omitempty"`
	// Capabilities represents the printer capabilities
	Capabilities *PrinterCapabilities `json:"capabilities,omitempty"`
	// LastSeen is when this printer was last seen by the agent
	LastSeen time.Time `json:"last_seen"`
	// CreatedAt is when this printer was first discovered
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// PrinterCapabilities represents the capabilities of a printer.
type PrinterCapabilities struct {
	// CanColor indicates if the printer supports color
	CanColor bool `json:"can_color"`
	// CanDuplex indicates if the printer supports duplex printing
	CanDuplex bool `json:"can_duplex"`
	// CanStaple indicates if the printer supports stapling
	CanStaple bool `json:"can_staple"`
	// CanPunch indicates if the printer supports hole punching
	CanPunch bool `json:"can_punch"`
	// SupportedMediaTypes is a list of supported media types (e.g., "a4", "letter")
	SupportedMediaTypes []string `json:"supported_media_types"`
	// SupportedPaperSizes is a list of supported paper sizes
	SupportedPaperSizes []string `json:"supported_paper_sizes"`
	// MaxResolution is the maximum DPI resolution
	MaxResolution int `json:"max_resolution"`
	// MinResolution is the minimum DPI resolution
	MinResolution int `json:"min_resolution"`
	// SupportedBins is a list of available paper bins/trays
	SupportedBins []string `json:"supported_bins"`
	// MaxCopies is the maximum number of copies that can be made
	MaxCopies int `json:"max_copies"`
}

// AgentInfo represents information about an agent.
type AgentInfo struct {
	// AgentID is the unique identifier for this agent
	AgentID string `json:"agent_id"`
	// Name is a human-readable name for the agent
	Name string `json:"name"`
	// Version is the agent software version
	Version string `json:"version"`
	// OS is the operating system (e.g., "Windows 10 Pro", "Windows 11")
	OS string `json:"os"`
	// Architecture is the system architecture (e.g., "amd64", "arm64")
	Architecture string `json:"architecture"`
	// Hostname is the machine hostname
	Hostname string `json:"hostname"`
	// Domain is the Windows domain (if joined)
	Domain string `json:"domain,omitempty"`
	// Username is the currently logged-in Windows user
	Username string `json:"username,omitempty"`
	// OrganizationID is the organization this agent belongs to
	OrganizationID string `json:"organization_id,omitempty"`
	// OwnerUserID is the user who owns/manages this agent (optional, for access control)
	OwnerUserID string `json:"owner_user_id,omitempty"`
	// Status is the current agent status
	Status AgentStatus `json:"status"`
	// SessionState is the current session state
	SessionState SessionState `json:"session_state,omitempty"`
	// PrinterCount is the number of discovered printers
	PrinterCount int `json:"printer_count"`
	// JobQueueDepth is the number of jobs in the agent's queue
	JobQueueDepth int `json:"job_queue_depth"`
	// LastHeartbeat is when the last heartbeat was received
	LastHeartbeat time.Time `json:"last_heartbeat"`
	// BootTime is when the agent/machine was started
	BootTime time.Time `json:"boot_time,omitempty"`
	// IPAddress is the agent's IP address
	IPAddress string `json:"ip_address,omitempty"`
	// MACAddress is the agent's MAC address
	MACAddress string `json:"mac_address,omitempty"`
	// CertificateThumbprint is the thumbprint of the agent's certificate
	CertificateThumbprint string `json:"certificate_thumbprint,omitempty"`
	// CreatedAt is when the agent was registered
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt is when the agent was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// HeartbeatRequest is sent by agents to report their status.
type HeartbeatRequest struct {
	// AgentID is the agent identifier
	AgentID string `json:"agent_id"`
	// Status is the current agent status
	Status AgentStatus `json:"status"`
	// SessionState is the current session state
	SessionState SessionState `json:"session_state,omitempty"`
	// PrinterCount is the number of discovered printers
	PrinterCount int `json:"printer_count"`
	// JobQueueDepth is the number of jobs currently queued
	JobQueueDepth int `json:"job_queue_depth"`
	// ActiveJobID is the ID of the currently processing job (if any)
	ActiveJobID string `json:"active_job_id,omitempty"`
	// Timestamp is when the heartbeat was generated
	Timestamp time.Time `json:"timestamp"`
	// Printers is the list of discovered printers (optional, for sync)
	Printers []DiscoveredPrinter `json:"printers,omitempty"`
}

// HeartbeatResponse is the server's response to a heartbeat.
type HeartbeatResponse struct {
	// Status indicates if the heartbeat was accepted
	Status string `json:"status"`
	// ServerTime is the current server time
	ServerTime time.Time `json:"server_time"`
	// PendingJobs is the count of jobs pending for this agent
	PendingJobs int `json:"pending_jobs"`
	// Commands is a list of commands the agent should execute
	Commands []AgentCommand `json:"commands,omitempty"`
	// ConfigurationUpdates contains any configuration updates
	ConfigurationUpdates map[string]interface{} `json:"configuration_updates,omitempty"`
}

// AgentCommand represents a command sent from the server to an agent.
type AgentCommand struct {
	// CommandID is a unique identifier for this command
	CommandID string `json:"command_id"`
	// Type is the command type (e.g., "refresh_printers", "shutdown", "update_config")
	Type string `json:"type"`
	// Payload contains command-specific data
	Payload json.RawMessage `json:"payload,omitempty"`
	// IssuedAt is when the command was issued
	IssuedAt time.Time `json:"issued_at"`
	// ExpiresAt is when the command expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
}

// PrinterDiscoveryRequest is sent when an agent registers discovered printers.
type PrinterDiscoveryRequest struct {
	// AgentID is the agent identifier
	AgentID string `json:"agent_id"`
	// Printers is the list of discovered printers
	Printers []DiscoveredPrinter `json:"printers"`
	// Replace indicates if this should replace all existing printers for this agent
	Replace bool `json:"replace"`
	// Timestamp is when the discovery was performed
	Timestamp time.Time `json:"timestamp"`
}

// PrinterDiscoveryResponse is the response to a printer discovery registration.
type PrinterDiscoveryResponse struct {
	// Registered is the count of newly registered printers
	Registered int `json:"registered"`
	// Updated is the count of updated printers
	Updated int `json:"updated"`
	// Unregistered is the count of printers that were removed
	Unregistered int `json:"unregistered"`
	// PrinterIDs maps local printer names to server IDs
	PrinterIDs map[string]string `json:"printer_ids"`
}

// JobPollRequest is sent by agents to poll for new jobs.
type JobPollRequest struct {
	// AgentID is the agent identifier
	AgentID string `json:"agent_id"`
	// Username is the Windows username to filter jobs for
	Username string `json:"username,omitempty"`
	// UserEmail is the user email to filter jobs for
	UserEmail string `json:"user_email,omitempty"`
	// Limit is the maximum number of jobs to return
	Limit int `json:"limit,omitempty"`
	// LastJobID is the ID of the last job received (for pagination)
	LastJobID string `json:"last_job_id,omitempty"`
	// Capabilities is the agent's current printer capabilities
	Capabilities map[string]*PrinterCapabilities `json:"capabilities,omitempty"`
}

// JobPollResponse contains jobs assigned to the agent.
type JobPollResponse struct {
	// Jobs is the list of pending jobs
	Jobs []AssignedJob `json:"jobs"`
	// HasMore indicates if there are more jobs available
	HasMore bool `json:"has_more"`
	// ServerTime is the current server time
	ServerTime time.Time `json:"server_time"`
}

// AssignedJob represents a print job assigned to an agent.
type AssignedJob struct {
	// JobID is the unique job identifier
	JobID string `json:"job_id"`
	// DocumentID is the document to print
	DocumentID string `json:"document_id"`
	// DocumentURL is the URL to download the document
	DocumentURL string `json:"document_url"`
	// DocumentChecksum is the SHA256 checksum of the document
	DocumentChecksum string `json:"document_checksum"`
	// DocumentSize is the document size in bytes
	DocumentSize int64 `json:"document_size"`
	// DocumentContentType is the document's content type
	DocumentContentType string `json:"document_content_type"`
	// PrinterID is the printer to use
	PrinterID string `json:"printer_id"`
	// PrinterName is the printer name
	PrinterName string `json:"printer_name"`
	// UserName is the user who submitted the job
	UserName string `json:"user_name"`
	// UserEmail is the user's email
	UserEmail string `json:"user_email"`
	// Title is the job title
	Title string `json:"title,omitempty"`
	// Copies is the number of copies
	Copies int `json:"copies"`
	// ColorMode is the color mode ("color" or "monochrome")
	ColorMode string `json:"color_mode"`
	// Duplex indicates if duplex printing is enabled
	Duplex bool `json:"duplex"`
	// MediaType is the paper type (e.g., "a4", "letter")
	MediaType string `json:"media_type"`
	// Quality is the print quality (e.g., "draft", "normal", "high")
	Quality string `json:"quality"`
	// Priority is the job priority (1-10)
	Priority int `json:"priority"`
	// Options contains additional print options
	Options map[string]string `json:"options,omitempty"`
	// CreatedAt is when the job was created
	CreatedAt time.Time `json:"created_at"`
	// RetryCount is the number of times this job has been retried
	RetryCount int `json:"retry_count,omitempty"`
}

// JobStatusUpdate is sent by agents to update job status.
type JobStatusUpdate struct {
	// JobID is the job identifier
	JobID string `json:"job_id"`
	// AgentID is the agent processing the job
	AgentID string `json:"agent_id"`
	// Status is the new job status
	Status string `json:"status"`
	// Message is a status message
	Message string `json:"message,omitempty"`
	// PagesPrinted is the number of pages printed so far
	PagesPrinted int `json:"pages_printed,omitempty"`
	// TotalPages is the total number of pages
	TotalPages int `json:"total_pages,omitempty"`
	// ErrorCode is an error code (if status is "failed")
	ErrorCode string `json:"error_code,omitempty"`
	// Timestamp is when the status update occurred
	Timestamp time.Time `json:"timestamp"`
	// DocumentChecksum is the checksum of the printed document
	DocumentChecksum string `json:"document_checksum,omitempty"`
}

// AgentRegistrationRequest is sent when a new agent registers.
type AgentRegistrationRequest struct {
	// Name is the agent name
	Name string `json:"name"`
	// Version is the agent version
	Version string `json:"version"`
	// OS is the operating system
	OS string `json:"os"`
	// Architecture is the system architecture
	Architecture string `json:"architecture"`
	// Hostname is the machine hostname
	Hostname string `json:"hostname"`
	// Domain is the Windows domain (if joined)
	Domain string `json:"domain,omitempty"`
	// Username is the logged-in user
	Username string `json:"username,omitempty"`
	// OrganizationID is the organization to join
	OrganizationID string `json:"organization_id,omitempty"`
	// EnrollmentToken is an optional enrollment token
	EnrollmentToken string `json:"enrollment_token,omitempty"`
	// CSR is a Certificate Signing Request for agent certificate
	CSR []byte `json:"csr,omitempty"`
	// MACAddress is the machine's MAC address
	MACAddress string `json:"mac_address,omitempty"`
}

// AgentRegistrationResponse is the response to agent registration.
type AgentRegistrationResponse struct {
	// AgentID is the assigned agent ID
	AgentID string `json:"agent_id"`
	// Certificate is the issued certificate (if CSR was provided)
	Certificate []byte `json:"certificate,omitempty"`
	// CertificateChain is the certificate chain
	CertificateChain [][]byte `json:"certificate_chain,omitempty"`
	// ServerPublicKey is the server's public key for secure communication
	ServerPublicKey []byte `json:"server_public_key,omitempty"`
	// Config is the initial agent configuration
	Config map[string]interface{} `json:"config,omitempty"`
	// HeartbeatInterval is the interval at which heartbeats should be sent
	HeartbeatInterval int `json:"heartbeat_interval"`
}

// AgentEvent represents an event logged by an agent.
type AgentEvent struct {
	// EventID is the unique event identifier
	EventID string `json:"event_id,omitempty"`
	// AgentID is the agent that generated the event
	AgentID string `json:"agent_id"`
	// Type is the event type (e.g., "printer_added", "job_completed", "error")
	Type string `json:"type"`
	// Severity is the event severity (e.g., "info", "warning", "error")
	Severity string `json:"severity"`
	// Message is the event message
	Message string `json:"message"`
	// Details contains additional event details
	Details map[string]interface{} `json:"details,omitempty"`
	// Timestamp is when the event occurred
	Timestamp time.Time `json:"timestamp"`
}

// DocumentDownloadRequest is used to request a document for printing.
type DocumentDownloadRequest struct {
	// DocumentID is the document identifier
	DocumentID string `json:"document_id"`
	// JobID is the job identifier
	JobID string `json:"job_id"`
	// AgentID is the agent requesting the document
	AgentID string `json:"agent_id"`
	// RangeStart is the starting byte for range requests (for resume)
	RangeStart int64 `json:"range_start,omitempty"`
	// Checksum is the expected checksum of the document
	Checksum string `json:"checksum,omitempty"`
}

// DocumentDownloadResponse contains the document data.
type DocumentDownloadResponse struct {
	// DocumentID is the document identifier
	DocumentID string `json:"document_id"`
	// Content is the document content
	Content []byte `json:"-"`
	// ContentType is the document's content type
	ContentType string `json:"content_type"`
	// ContentLength is the document size
	ContentLength int64 `json:"content_length"`
	// Checksum is the SHA256 checksum of the document
	Checksum string `json:"checksum"`
	// SupportsResume indicates if the download can be resumed
	SupportsResume bool `json:"supports_resume"`
	// TotalSize is the total file size
	TotalSize int64 `json:"total_size"`
}

// AgentCertificate represents an agent's X.509 certificate.
type AgentCertificate struct {
	// CertificateID is the unique identifier
	CertificateID string `json:"certificate_id,omitempty"`
	// AgentID is the agent this certificate belongs to
	AgentID string `json:"agent_id"`
	// SerialNumber is the certificate serial number
	SerialNumber string `json:"serial_number"`
	// Thumbprint is the certificate thumbprint
	Thumbprint string `json:"thumbprint"`
	// Subject is the certificate subject
	Subject string `json:"subject"`
	// Issuer is the certificate issuer
	Issuer string `json:"issuer"`
	// NotValidBefore is the certificate validity start
	NotValidBefore time.Time `json:"not_valid_before"`
	// NotValidAfter is the certificate validity end
	NotValidAfter time.Time `json:"not_valid_after"`
	// IsRevoked indicates if the certificate has been revoked
	IsRevoked bool `json:"is_revoked"`
	// RevokedAt is when the certificate was revoked
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// RevocationReason is the reason for revocation
	RevocationReason string `json:"revocation_reason,omitempty"`
	// CreatedAt is when the certificate was issued
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// WebSocketMessage represents a message sent over WebSocket.
type WebSocketMessage struct {
	// Type is the message type
	Type string `json:"type"`
	// Data is the message payload
	Data json.RawMessage `json:"data"`
	// Timestamp is when the message was sent
	Timestamp time.Time `json:"timestamp"`
}

// WebSocketMessage types
const (
	// MessageTypeJobUpdate indicates a job status update
	MessageTypeJobUpdate = "job.update"
	// MessageTypeNewJob indicates a new job assignment
	MessageTypeNewJob = "job.new"
	// MessageTypeCommand indicates a server command
	MessageTypeCommand = "agent.command"
	// MessageTypeConfigUpdate indicates a configuration update
	MessageTypeConfigUpdate = "agent.config"
	// MessageTypePrinterUpdate indicates a printer status update
	MessageTypePrinterUpdate = "printer.update"
	// MessageTypeHeartbeatAck acknowledges a heartbeat
	MessageTypeHeartbeatAck = "heartbeat.ack"
)
